#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Public fixed-setting template for the PaperFour HAPPO experiments.

This template is intentionally not a standalone training configuration. It
documents the fixed control boundary used by PaperFour without exposing raw
reservoir workbooks, inflow workbooks, database settings, checkpoints, or local
machine paths. The executable project configuration is generated by
`PaperFour_run_experiments.py` from the private project environment.
"""

FIXED_SYSTEM = {
    "reservoir_system_file": "ResStr5.xlsx",
    "reservoir_system_public_status": "restricted_input_file_not_included",
    "algorithm": "HAPPO",
    "observation_setting": "fixed observation setting",
    "observation_implementation_label": "local reservoir variables plus shared cascade-level context",
    "reward_formulation": "default reward formulation",
    "action_representation": "discrete",
    "action_dim": 100,
    "daily_steps_per_episode": 1825,
    "data_export_mode": "excel",
}

FIXED_STAGE_B_BUDGET = {
    "max_episodes": 50,
    "collector_env_num": 10,
    "data_export_count": 10,
    "seed_rule": "seed = round * 100",
    "stage_b_seeds": [100, 200, 300],
}

LEARNING_DYNAMICS_DEFAULTS = {
    "learning_rate": 5e-4,
    "critic_learning_rate": 5e-4,
    "clip_ratio": 0.2,
    "entropy_weight": 0.016,
    "discount_factor": 0.995,
    "gae_lambda": 0.95,
}

LEARNING_DYNAMICS_CANDIDATE_VALUES = {
    "learning_rate": [1e-4, 3e-4, 5e-4, 1e-3],
    "critic_learning_rate": [1e-4, 3e-4, 5e-4, 1e-3],
    "clip_ratio": [0.1, 0.2, 0.3],
    "entropy_weight": [0.004, 0.008, 0.016, 0.032],
    "discount_factor": [0.99, 0.995, 0.999],
    "gae_lambda": [0.90, 0.95, 0.98],
}

METRIC_DIRECTIONS = {
    "return": "higher_better",
    "generation": "higher_better",
    "action_correction": "lower_better",
    "violation_rates": "lower_better",
    "lower_bound_water_level_pressure": "lower_better",
    "conditional_spillage_diagnostics": "directional_risk",
    "total_spillage": "neutral_spillage_diagnostic",
    "flood_season_spillage": "neutral_spillage_diagnostic",
}

INTERPRETATION_BOUNDARY = [
    "fixed five-reservoir HAPPO setting",
    "fixed observation setting",
    "fixed reward formulation",
    "fixed action representation",
    "sampled Stage B learning-dynamics matrix",
    "one Stage C mixed-sequence checkpoint validation",
    "no claim of transferable parameter prescription",
]
